print("=" * 75)
print("  BUGUNKU 3 MAC - HER MARKET ICIN DURUM RAPORU")
print("=" * 75)
print()

# ═══════════════════════════════════════════════════════════════
# MAC 1: BASEKSEHIR vs GALATASARAY
# ═══════════════════════════════════════════════════════════════
print("-" * 75)
print("  1) BASEKSEHIR vs GALATASARAY (Super Lig, 20:00)")
print("-" * 75)
print()
print("  TOPLAM GOL:")
print("    Model:  U1.5=85.8%  U2.5=66.2%  U3.5=47.4%")
print("    Iddaa:  U2.5=1.38 (73%)  Alt2.5=2.48 (40%)")
print("    -> Model U2.5=66% vs Piyasa 73%. Iyi ama biraz dusuk.")
print("    -> Beklenen gol: 2.48. Iddaa'dan daha dusuk beklenti.")
print("    TUTMA ORANI: IYI (yakin, ama model biraz muhafazakar)")
print()
print("  BTTS:")
print("    Model:  Evet=67.0%  Hayir=33.0%")
print("    Iddaa:  BTTS yok direkt, ama GS favori + gol beklentisi yuksek")
print("    -> GS deplasmanda gol atiyor (Osimhen 5 mac 5 gol)")
print("    -> Basaksehir de evinde gol atiyor (son 8 macin 6'sinda)")
print("    TUTMA ORANI: IYI (67% makul)")
print()
print("  CIFTE SANS:")
print("    1X: 75.1%  |  12: 78.4%  |  X2: 46.5%")
print("    Iddaa: 1-X=1.05 (~95%)  |  1-2=2.11 (~47%)  |  X-2=1.08 (~93%)")
print("    -> Model 1X=75% vs Iddaa 95%!! COK FARK VAR!")
print("    -> Model GS'nin kazanma sansini dusuk gosteriyor")
print("    TUTMA ORANI: KOTU (1X cok dusuk, 12 de dusuk)")
print()
print("  KORNER:")
print("    Model: Toplam=7.0  U7.5=40.1%  U8.5=27.1%")
print("    -> DUSUK! 7 korner bekliyor, U7.5 bile %40")
print("    TUTMA ORANI: KOTU (korner tahmini zayif)")
print()
print("  ** OZET: Gol Ust ve BTTS iyi. CiftSans ve Korner KOTU **")
print()

# ═══════════════════════════════════════════════════════════════
# MAC 2: STUTTGART vs KOLN
# ═══════════════════════════════════════════════════════════════
print("-" * 75)
print("  2) STUTTGART vs KOLN (Bundesliga, 20:30)")
print("-" * 75)
print()
print("  TOPLAM GOL:")
print("    Model:  U1.5=83.9%  U2.5=67.0%  U3.5=45.6%")
print("    Piyasa: U2.5=1.37 (73%)  BTTS=1.50 (67%)")
print("    -> Model U2.5=67% vs Piyasa 73%. Yakin!")
print("    -> Beklenen gol: 3.46! COK YUKSEK! U3.5 bile 45.6%")
print("    TUTMA ORANI: IYI (gol beklentisi yuksek, makul)")
print()
print("  BTTS:")
print("    Model:  Evet=57.5%  Hayir=42.5%")
print("    Piyasa: BTTS=1.50 (67%)")
print("    -> Model 57.5% vs Piyasa 67%. Model biraz dusuk!")
print("    -> Koln son 5 macta 80% BTTS yapti")
print("    -> H2H son 6 macin tamami BTTS")
print("    TUTMA ORANI: ORTA (model biraz dusuk, piyasa daha yuksek)")
print()
print("  CIFTE SANS:")
print("    1X: 87.4%  |  12: 79.7%  |  X2: 32.9%")
print("    -> 1X=87.4% COK YUKSEK! Stuttgart favori + beraberlik")
print("    -> 12=79.7% de guclu (bir taraf kesin atar)")
print("    TUTMA ORANI: IYI (1X cok guclu)")
print()
print("  KORNER:")
print("    Model: Toplam=7.4  U7.5=46.6%  U8.5=32.9%")
print("    -> DUSUK! 7.4 korner bekliyor")
print("    TUTMA ORANI: KOTU (korner tahmini zayif)")
print()
print("  ** OZET: Gol Ust ve CiftSans 1X iyi. BTTS biraz dusuk. Korner KOTU **")
print()

# ═══════════════════════════════════════════════════════════════
# MAC 3: IPSWICH vs LIVERPOOL
# ═══════════════════════════════════════════════════════════════
print("-" * 75)
print("  3) IPSWICH vs LIVERPOOL (Premier Lig, 20:00 UK)")
print("-" * 75)
print()
print("  TOPLAM GOL:")
print("    Model:  U1.5=84.5%  U2.5=64.3%  U3.5=43.4%")
print("    Piyasa: U2.5=1.36 (74%)  BTTS=1.50 (67%)")
print("    -> Model U2.5=64% vs Piyasa 74%. 10% FARK!")
print("    -> Beklenen gol: 3.63! COK YUKSEK!")
print("    TUTMA ORANI: ORTA (model piyasadan daha dusuk)")
print()
print("  BTTS:")
print("    Model:  Evet=65.0%  Hayir=35.0%")
print("    Piyasa: BTTS=1.50 (67%)")
print("    -> Model 65% vs Piyasa 67%. IYI EŞIT!")
print("    -> Liverpool son 2 macta BTTS yaptı")
print("    -> Ipswich son 2 macta BTTS yapti")
print("    TUTMA ORANI: IYI (cok yakin)")
print()
print("  CIFTE SANS:")
print("    1X: 76.8%  |  12: 79.2%  |  X2: 43.9%")
print("    -> 1X=76.8%! Ama Liverpool favori!")
print("    -> Model ev sahibi + beraberlik diyor ama piyasa Liverpool diyor")
print("    -> 12=79.2% Makul (bir taraf kesin atar)")
print("    TUTMA ORANI: ORTA (1X yanlis tarafa bakabilir)")
print()
print("  KORNER:")
print("    Model: Toplam=11.5  U7.5=88.4%  U8.5=80.6%  U9.5=70.7%")
print("    -> 11.5 korner! COK YUKSEK! U7.5=88%!")
print("    -> PL maci, iki takim da atak, korner yuksek olabilir")
print("    TUTMA ORANI: IYI (korner yuksek, U7.5 guclu)")
print()
print("  ** OZET: BTTS iyi. Korner Ust 7.5 cok guclu! Gol biraz dusuk. **")
print()

# ═══════════════════════════════════════════════════════════════
# SONU TABLOSU
# ═══════════════════════════════════════════════════════════════
print("=" * 75)
print("  MARKET MARKET SONUC TABLOSU")
print("=" * 75)
print()
print("  MAC                  | Gol U2.5 | BTTS  | CiftSans   | Korner")
print("  ---------------------|----------|-------|------------|--------")
print("  Basaksehir-Galatasaray|  IYI(66) | IYI(67)| KOTU(75)  | KOTU(7)")
print("  Stuttgart-Koln        |  IYI(67) | ORTA(58)| IYI(87)  | KOTU(7)")
print("  Ipswich-Liverpool     |  ORTA(64)| IYI(65)| ORTA(77)  | IYI(11)")
print()
print("  EN IYI MARKETLER:")
print("    1. BTTS Evet (3 macin 2'sinde >65%)")
print("    2. Gol Ust 2.5 (3 macin tamami >64%)")
print("    3. Korner Ust 7.5 (sadece Ipswich-Liv'de guclu: %88)")
print()
print("  EN KOTU MARKETLER:")
print("    1. Korner (2 macin 2'sinde 7.0-7.4 = cok dusuk)")
print("    2. CiftSans (Basaksehir-GS'de 1X=75% ama GS favori!)")
print()
print("  ONEMLI NOT:")
print("    1X2'de model ev sahibine biasli. Ama diger marketlerde")
print("    gol ve BTTS tahminleri piyasaya yakin ve MAKUL.")
print("    ozellikle BTTS ve Gol Ust'te model makul calisiyor.")
print()
