print("=" * 90)
print("  BUGUNKU MAC - MODEL TAHMIN vs PIYASA (4 Eylul 2026)")
print("=" * 90)
print()
print("-" * 90)
print("  MAC 1: BASEKSEHIR vs GALATASARAY - Super Lig 4. Hafta (20:00)")
print("-" * 90)
print()
print("  MODEL TAHMINI:")
print("    1X2:  H=53.5%  D=21.6%  A=24.9%  -> Favori: EV SAHIBI")
print("    O2.5: 66.2%    BTTS: 67.0%")
print("    Gol:  Ev Lambda=1.63  Dep Lambda=0.86  Toplam=2.48")
print()
print("  IDDAA ORANLARI (mackolik):")
print("    1X2:  1=4.81  X=4.28  2=1.45  -> Favori: GALATASARAY")
print("    O2.5: 1.38    Alt2.5: 2.48")
print()
print("  ANALIZ:")
print("    ** MODEL TAMAMEN YANLIS TARAFTA! **")
print("    Model: 53.5% Ev sahibi favori  vs  Iddaa: 69.4% GS favori (1/1.45)")
print("    Fark: ~16%! Model, piyasanin tam tersini soyluyor.")
print("    Galatasaray deplasmanda bile favori (Osimhen 5 gol, 3 mac)")
print("    Baseksehir son 8 lig macinda GS'yi yenemedi (3B 5M)")
print("    SONUC: Model bu masta YANILMIS OLACAK")
print()

print("-" * 90)
print("  MAC 2: STUTTGART vs KOLN - Bundesliga 2. Hafta (20:30)")
print("-" * 90)
print()
print("  MODEL TAHMINI:")
print("    1X2:  H=67.1%  D=20.3%  A=12.6%  -> Favori: EV SAHIBI")
print("    O2.5: 67.0%    BTTS: 57.5%")
print("    Gol:  Ev Lambda=2.06  Dep Lambda=1.45  Toplam=3.51")
print()
print("  PIYASA ORANLARI:")
print("    1X2:  1=1.44 (69%)  X=4.00 (25%)  2=5.00 (20%)  -> Favori: STUTTGART")
print("    O2.5: ~1.37 (~73%)  BTTS: ~1.50 (~67%)")
print()
print("  ANALIZ:")
print("    ** MODEL DOGRU TARAFTA! **")
print("    Model: 67.1% Ev  vs  Piyasa: 69% Ev -> Fark sadece ~2%")
print("    Draw: Model 20.3%  vs  Piyasa 25% -> Model biraz dusuk")
print("    Away: Model 12.6%  vs  Piyasa 20% -> Koln son 5'te 3B")
print("    H2H: Stuttgart son 2 maci kazandi (3-1, 2-1)")
print("    Koln: Waldschmidt + Huubers yok, ciddi eksiklikler")
print("    SONUC: Model burada makul bir tahmin yapiyor")
print()

print("-" * 90)
print("  MAC 3: IPSWICH vs LIVERPOOL - Premier League 3. Hafta (20:00 UK)")
print("-" * 90)
print()
print("  MODEL TAHMINI:")
print("    1X2:  H=56.1%  D=20.8%  A=23.2%  -> Favori: EV SAHIBI (!)")
print("    O2.5: 64.3%    BTTS: 65.0%")
print("    Gol:  Ev Lambda=1.58  Dep Lambda=1.52  Toplam=3.10")
print()
print("  PIYASA ORANLARI:")
print("    1X2:  1=5.60 (18%)  X=4.70 (21%)  2=1.52 (66%)  -> Favori: LIVERPOOL")
print("    O2.5: ~1.36 (~74%)  BTTS: ~1.50 (~67%)")
print()
print("  ANALIZ:")
print("    ** MODEL TAMAMEN YANLIS TARAFTA! **")
print("    Model: 56.1% Ev sahibi favori  vs  Piyasa: 66% Liverpool favori")
print("    Fark: ~48%! Model, Liverpool'un kazanma olasiligini 23% gosteriyor")
print("    Gercekte Liverpool 66% favori (1/1.52)")
print("    Liverpool: 2 beraberlik, 0 galibiyet ama hala lig favorisi")
print("    Ipswich: 1G 1M, Man United'a 5-2 yenildi")
print("    SONUC: Model bu masta YANILMIS OLACAK")
print()

print("=" * 90)
print("  GENEL DEGERLENDIRME")
print("=" * 90)
print()
print("  MAC     | MODEL FAVORI        | PIYASA FAVORI     | DURUM")
print("  --------|---------------------|-------------------|--------")
print("  GS-Bas  | Ev Sahibi (53.5%)   | Galatasaray        | YANLIS")
print("  Stu-Kol | Ev Sahibi (67.1%)   | Stuttgart          | DOGRU")
print("  Ips-Liv | Ev Sahibi (56.1%)   | Liverpool          | YANLIS")
print()
print("  SONUC: 3 macin 2'sinde model YANLIS tarafa bakiyor!")
print()
print("  KRITIK SORUN:")
print("  Model neredeyse HER MACTA ev sahibini favori gosteriyor!")
print("  Bu, modelin ciddi bir home-bias sorunu oldugunu gosteriyor.")
print()
print("  NEDEN BOYLE?")
print("  1. mkt_home_prob feature'i piyasa oranlarindan geliyor")
print("     Ama model bu sinyali dogru ogrenememis")
print("  2. LightGBM modeli ev sahibi avantajini asiri ogrenmis")
print("  3. Kalibrasyon isotonic regression ile yapilmis ama")
print("     piyasa oranlari zaten kalibreli - model bozmus")
print()
print("  ONERI:")
print("  - mkt_home_prob feature'ini CIKAR -> model kendi basina ogrensin")
print("  - Piyasa oranlarini dogrudan kullan (modeli bypass et)")
print("  - Veya modeli sifirdan egit, sadece futbol feature'lariyla")
print()
